import pandas as pd


def calculate_sales_metrics(df: pd.DataFrame) -> dict:
    """Calculate core business sales metrics."""

    metrics = {
        "total_revenue": float(df["revenue"].sum()),
        "total_transactions": int(df["invoice"].nunique()),
        "total_products": int(df["stock_code"].nunique()),
        "total_customers": int(df["customer_id"].nunique()),
        "total_countries": int(df["country"].nunique()),
        "average_order_value": float(
            df.groupby("invoice")["revenue"].sum().mean()
        ),
    }

    return metrics


def monthly_sales(df: pd.DataFrame) -> pd.DataFrame:
    """Calculate monthly revenue."""

    result = (
        df.assign(
            year_month=df["invoice_date"].dt.to_period("M")
        )
        .groupby("year_month")["revenue"]
        .sum()
        .reset_index()
    )

    result["year_month"] = result["year_month"].dt.to_timestamp()

    return result

def top_products(df:pd.DataFrame,n:int=10)->pd.DataFrame:
    """Return top products by revenue"""
    result=(
        df.groupby("stock_code")["revenue"]
        .sum()
        .sort_value(ascending=False)
        .head(n)
        .reset_index()
    )
    return result

def top_countries(df:pd.DataFrame,n:int=10)->pd.DataFrame:
    """Return top countries by revenue."""
    result=(
        df.groupby("country")['revenue']
        .sum()
        .sort_values(ascending=False)
        .head(n)
        .reset_index()
    )
    return result

def customer_revenue(df:pd.DataFrame)->pd.DataFrame:
    """Calculate total revenue generated by each customer."""
    result=(
        df.groupby("customer_id")["revenue"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()

    )
    return result